name: Model Workflow

on:
  push:
    branches:
      - main


jobs:
  test:
      runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8.15'

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests
      run: python -m pytest test_ml.py
      
  deploy:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.15'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Start FastAPI server
        run: uvicorn main:app --host 0.0.0.0 --port 8000
