name: Model Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run_model:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Model
      run: python /Users/kaleymayer/Deploying-a-Scalable-ML-Pipeline-with-FastAPI/main.py

  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Deploy FastAPI application
        run: uvicorn main:app --host 0.0.0.0 --port 8000
