name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download census.csv
      run: |
        mkdir -p data
        wget -O data/census.csv https://raw.githubusercontent.com/ksavage87/Deploying-a-Scalable-ML-Pipeline-with-FastAPI/main/data/census.csv


    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.15

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Adjust the filename as needed

    - name: Run Flake8
      run: |
        pip install flake8
        flake8

    - name: Run tests
      run: pytest
